const dataCategorias = [
  // Categorias de Gastos
  {
    id: 1,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupos: ['Comercios', 'Comida', 'Despensa'],
    subgrupos: {
      Comercios: ['Restaurante', 'Café', 'Bar'],
      Comida: ['A Domicilio', 'Callejera', 'Comida Rápida', 'Tiendita'],
      Despensa: ['Mercado', 'Supermercado'],
    },
  },
  {
    id: 2,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupos: [
      'Accesorios',
      'Artículos para el Hogar',
      'Electrónica',
      'Herramientas',
      'Higiene Personal',
      'Muebles',
      'Oficina',
      'Productos de Limpieza para el Hogar',
      'Regalos',
      'Ropa y Calzado',
      'Tiempo libre',
    ],
    subgrupos: [],
  },
  {
    id: 3,
    categoria: 'Gastos Financieros',
    categoriaEmoji: '🛒',
    grupos: ['Servicios', 'Intereses', 'Comisiones'],
  },

  {
    id: 4,
    categoria: 'Mascota',
    categoriaEmoji: '🐾',
    grupos: [
      'Baño',
      'Croquetas',
      'Juguetes y Accesorios',
      'Medicinas y Suplementos',
      'Otros',
      'Veterinario',
    ],
    subgrupos: [],
  },
  {
    id: 5,
    categoria: 'Tecnologia',
    categoriaEmoji: '💻',
    grupos: ['Hardware', 'Software&Apps', 'Telefonia Móvil', 'Web'],
    subgrupos: {
      'Software&Apps': ['Nube', 'Apps', 'Suscripciones', 'Software'],
      Web: ['Alojamiento', 'Desarrollo', 'Dominios'],
      'Telefonia Móvil': ['Accesorios', 'Planes', 'Recargas'],
      Hardware: ['Computadora', 'Periféricos', 'Componentes', 'Video'],
    },
  },
  {
    id: 6,
    categoria: 'Transporte',
    categoriaEmoji: '🚗',
    grupos: ['Automovil', 'Bicicleta', 'Taxi', 'Transporte Público'],
    subgrupos: {
      Automovil: ['Estacionamiento', 'Gasolina', 'Mantenimiento'],
      Bicicleta: ['Accesorios', 'Mantenimiento'],
      Taxi: ['Viajes'],
      'Transporte Público': [],
    },
  },
  {
    id: 7,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupos: [
      'Juegos de Azar | Apuestas',
      'Malos Vicios',
      'Viajes',
      'TV Streaming',
      'Libros | Audio',
      'Educación y Desarrollo',
      'Pasatiempos',
      'Eventos Sociales',
      'Eventos',
      'Fitness',
      'Cuidado Personal',
      'Salud',
    ],
    subgrupos: {
      'Juegos de Azar | Apuestas': ['Loteria', 'Casino', 'Apuestas Deportivas'],
      'Malos Vicios': ['Cigarros', 'Alcohol', 'Otros'],
      Viajes: ['Comida', 'Avión', 'Hospedaje', 'Transporte', 'Otros'],
      'TV Streaming': [],
      'Libros | Audio': ['Libros Fisicos', 'Ebooks', 'Audiolibros'],
      'Educación y Desarrollo': ['Cursos', 'Libros', 'Conferencias', 'Otros'],
      Pasatiempos: ['Clases de Baile', 'Batucada', 'Otros'],
      'Eventos Sociales': ['Cumpleaños', 'Bodas', 'Reuniones', 'Otros'],
      Eventos: ['Cine', 'Conciertos', 'Teatro', 'Otros'],
      Fitness: ['Gym', 'Clases', 'Equipo', 'Futbol', 'Yoga'],
      'Cuidado Personal': ['Peluquería', 'Spa'],
      Salud: [
        'Farmacia',
        'Medicinas',
        'Dentista',
        'Consultas Médicas',
        'Exámenes',
        'Terapias',
        'Fisioterapia',
      ],
    },
  },
  {
    id: 8,
    categoria: 'Vivienda',
    categoriaEmoji: '🏠',
    grupos: [
      'Mantenimiento Y Reparaciones',
      'Servicios',
      'Internet y Telefonía',
      'Limpieza del Hogar',
      'Mantenimiento Copilco',
    ],
    subgrupos: {
      'Mantenimiento Y Reparaciones': ['Fontanería', 'Electricidad', 'Carpintería'],
      Servicios: ['Gas', 'Agua', 'Luz', 'Recolección de Basura'],
      'Internet y Telefonía': ['Teléfono', 'Internet'],
      'Limpieza del Hogar': ['Productos de Limpieza', 'Servicios de Limpieza'],
      'Mantenimiento Copilco': ['Reparaciones', 'Cuotas de Mantenimiento'],
    },
  },
];

const categoriasArray = [
  'Alimentos',
  'Compras',
  'Gastos Financieros',
  'Mascota',
  'Tecnologia',
  'Transporte',
  'Vida y Entretenimiento',
  'Vivienda',
];
const categoriaEmojis = {
  Alimentos: '🍽️',
  Compras: '🛒',
  'Gastos Financieros': '💳',
  Mascota: '🐾',
  Tecnologia: '💻',
  Transporte: '🚗',
  'Vida y Entretenimiento': '🎉',
  Vivienda: '🏠',
};

const gruposArray = {
  Alimentos: ['Comercios', 'Comida', 'Despensa'],
  Compras: ['Accesorios', 'Artículos para el Hogar', 'Electrónica'],
  'Gastos Financieros': ['Servicios', 'Intereses', 'Comisiones'],
  Mascota: ['Alimentos', 'Veterinario', 'Accesorios'],
  Tecnologia: ['Hardware', 'Software', 'Suscripciones'],
  Transporte: ['Gasolina', 'Mantenimiento', 'Transporte Público'],
  'Vida y Entretenimiento': ['Salidas', 'Cine', 'Música'],
  Vivienda: ['Renta', 'Servicios', 'Mantenimiento'],
};

const grupoEmojis = {
  Comercios: '🏪',
  Comida: '🍔',
  Despensa: '🛒',
  Accesorios: '🧢',
  'Artículos para el Hogar': '🏠',
  Electrónica: '💻',
  Herramientas: '🔧',
  'Higiene Personal': '🧴',
  Muebles: '🛋️',
  Oficina: '📎',
  'Productos de Limpieza para el Hogar': '🧽',
  Regalos: '🎁',
  'Ropa y Calzado': '👟',
  'Tiempo libre': '🎲',
  'Gastos Financieros': '💳',
  Mascota: '🐶',
  'Telefonia Móvil': '📱',
  Web: '🌐',
  Automovil: '🚗',
  Bicicleta: '🚲',
  Taxi: '🚕',
  'Transporte Público': '🚌',
  'Cuidado Personal': '💆',
  'Educación y Desarrollo': '🎓',
  'Eventos Fuera de Casa': '🎭',
  'Eventos Sociales': '🎉',
  Fitness: '🏋️',
  'Juegos de Azar | Apuestas': '🎰',
  'Libros | Audio': '📖',
  'Malos Vicios': '🚬',
  Pasatiempos: '🎵',
  Salud: '🏥',
  Streaming: '🎬',
  Viajes: '✈️',
  Vivienda: '🏠',
};

const subgruposArray = {
  Comercios: ['Restaurante', 'Café', 'Bar'],
  Comida: ['Supermercado', 'Tianguis', 'Comida Rápida'],
  'Gastos Financieros': ['Servicios', 'Intereses', 'Comisiones'],
  Mascota: ['Alimentos', 'Veterinario', 'Accesorios'],
  Tecnologia: ['Hardware', 'Software', 'Suscripciones'],
  Transporte: ['Gasolina', 'Mantenimiento', 'Transporte Público'],
  'Vida y Entretenimiento': ['Salidas', 'Cine', 'Música'],
  Vivienda: ['Renta', 'Servicios', 'Mantenimiento'],
};

const subgrupoEmojis = {
  Bar: '🍺',
  Café: '☕',
  Restaurante: '🍽️',
  'A Domicilio': '🏠',
  Callejera: '🌮',
  'Comida Rápida': '🍔',
  Tianguis: '🛒',
  Tiendita: '🏪',
  Mercado: '🥬',
  Supermercado: '🛒',
  Servicios: '💳',
  Intereses: '💳',
  Comisiones: '💳',
  Alimentos: '🍖',
  Veterinario: '🐶',
  Accesorios: '🧸',
  Hardware: '💻',
  Software: '🖥️',
  Suscripciones: '🔔',
  Gasolina: '⛽',
  Mantenimiento: '🛠️',
  'Transporte Público': '🚌',
  Salidas: '🎉',
  Cine: '🎬',
  Música: '🎵',
  Renta: '🏠',
  Servicios: '📶',
  Mantenimiento: '🧹',
};

const rawDataCategoriasGastos = [
  // Alimentos
  {
    id: 1,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comercios',
    grupoEmoji: '🏪',
    subgrupo: 'Bar',
    subgrupoEmoji: '🍺',
    tipo: '',
    helperKey: '',
  },
  {
    id: 2,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comercios',
    grupoEmoji: '🏪',
    subgrupo: 'Café',
    subgrupEmoji: '☕',
    tipo: '',
    helperKey: '',
  },
  {
    id: 3,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comercios',
    grupoEmoji: '🏪',
    subgrupo: 'Restaurante',
    subgrupEmoji: '🍽️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 4,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comida',
    grupoEmoji: '🍔',
    subgrupo: 'A Domicilio',
    subgrupEmoji: '🏠',
    tipo: '',
    helperKey: '',
  },
  {
    id: 5,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comida',
    grupoEmoji: '🍔',
    subgrupo: 'Callejera',
    subgrupEmoji: '🌮',
    tipo: '',
    helperKey: '',
  },
  {
    id: 6,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comida',
    grupoEmoji: '🍔',
    subgrupo: 'Comida Rápida',
    subgrupEmoji: '🍔',
    tipo: '',
    helperKey: '',
  },
  {
    id: 7,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comida',
    grupoEmoji: '🍔',
    subgrupo: 'Tianguis',
    subgrupEmoji: '🛒',
    tipo: '',
    helperKey: '',
  },
  {
    id: 8,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Comida',
    grupoEmoji: '🍔',
    subgrupo: 'Tiendita',
    subgrupEmoji: '🏪',
    tipo: '',
    helperKey: '',
  },
  {
    id: 9,
    categoria: 'Alimentos',
    categoriaEmoji: '🍽️',
    grupo: 'Despensa',
    grupoEmoji: '🛒',
    subgrupo: 'Mercado',
    subgrupEmoji: '🥬',
    tipo: '',
    helperKey: '',
  },
  {
    id: 10,
    categoriaEmoji: '🍽️',
    categoria: 'Alimentos',
    grupoEmoji: '🛒',
    grupo: 'Despensa',
    subgrupEubgrupo: 'Supermercado',
    tipo: '',
    helperKey: '',
  },
  // Compras
  {
    id: 11,
    categoriaEmoji: '🛒',
    categoria: 'Compras',
    grupoEmoji: '🧢',
    grupo: 'Accesorios',
    subgrupEubgrupo: '',
    tipo: '',
    helperKey: '',
  },
  {
    id: 12,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Artículos para el Hogar',
    grupoEmoji: '🏠',
    subgrupo: '',
    subgrupEmoji: '🏠',
    tipo: '',
    helperKey: '',
  },
  {
    id: 13,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Electrónica',
    grupoEmoji: '💻',
    subgrupo: '',
    subgrupEmoji: '💻',
    tipo: '',
    helperKey: '',
  },
  {
    id: 14,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Herramientas',
    grupoEmoji: '🔧',
    subgrupo: '',
    subgrupEmoji: '🔧',
    tipo: '',
    helperKey: '',
  },
  {
    id: 15,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Higiene Personal',
    grupoEmoji: '🧴',
    subgrupo: '',
    subgrupEmoji: '🧴',
    tipo: '',
    helperKey: '',
  },
  {
    id: 16,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Muebles',
    grupoEmoji: '🛋️',
    subgrupo: '',
    subgrupEmoji: '🛋️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 17,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Oficina',
    grupoEmoji: '📎',
    subgrupo: '',
    subgrupEmoji: '📎',
    tipo: '',
    helperKey: '',
  },
  {
    id: 18,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Productos de Limpieza para el Hogar',
    grupoEmoji: '🧽',
    subgrupo: '',
    subgrupEmoji: '🧽',
    tipo: '',
    helperKey: '',
  },
  {
    id: 19,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Regalos',
    grupoEmoji: '🎁',
    subgrupo: '',
    subgrupEmoji: '🎁',
    tipo: '',
    helperKey: '',
  },
  {
    id: 20,
    categoriaEmoji: '🛒',
    categoria: 'Compras',
    grupoEmoji: '👟',
    grupo: 'Ropa y Calzado',
    subgrupEubgrupo: '',
    tipo: '',
    helperKey: '',
  },
  {
    id: 21,
    categoria: 'Compras',
    categoriaEmoji: '🛒',
    grupo: 'Tiempo libre',
    grupoEmoji: '🎲',
    subgrupo: '',
    subgrupEmoji: '🎲',
    tipo: '',
    helperKey: '',
  },
  // Gastos Financieros
  {
    id: 22,
    categoria: 'Gastos Financieros',
    categoriaEmoji: '💳',
    grupo: 'Comisiones',
    grupoEmoji: '💳',
    subgrupo: '',
    subgrupEmoji: '💳',
    tipo: '',
    helperKey: '',
  },
  {
    id: 23,
    categoria: 'Gastos Financieros',
    categoriaEmoji: '💳',
    grupo: 'Impuestos',
    grupoEmoji: '💳',
    subgrupo: '',
    subgrupEmoji: '🧾',
    tipo: '',
    helperKey: '',
  },
  {
    id: 24,
    categoria: 'Gastos Financieros',
    categoriaEmoji: '💳',
    grupo: 'Seguros',
    grupoEmoji: '💳',
    subgrupo: '',
    subgrupEmoji: '📈',
    tipo: '',
    helperKey: '',
  },
  // Mascota
  {
    id: 25,
    categoria: 'Mascota',
    categoriaEmoji: '🐾',
    grupo: 'Baño',
    grupoEmoji: '🐶',
    subgrupo: '',
    subgrupEmoji: '🛁',
    tipo: '',
    helperKey: '',
  },
  {
    id: 26,
    categoria: 'Mascota',
    categoriaEmoji: '🐾',
    grupo: 'Croquetas',
    grupoEmoji: '🐶',
    subgrupo: '',
    subgrupEmoji: '🍖',
    tipo: '',
    helperKey: '',
  },
  {
    id: 27,
    categoria: 'Mascota',
    categoriaEmoji: '🐾',
    grupo: 'Juguetes y Accesorios',
    grupoEmoji: '🐶',
    subgrupo: '',
    subgrupEmoji: '🧸',
    tipo: '',
    helperKey: '',
  },
  {
    id: 28,
    categoria: 'Mascota',
    categoriaEmoji: '🐾',
    grupo: 'Medicinas y Suplementos',
    grupoEmoji: '🐶',
    subgrupo: '',
    subgrupEmoji: '💊',
    tipo: '',
    helperKey: '',
  },
  {
    id: 29,
    categoria: 'Mascota',
    categoriaEmoji: '🐾',
    grupo: 'Otros',
    grupoEmoji: '🐶',
    subgrupo: '',
    subgrupEmoji: '🔎',
    tipo: '',
    helperKey: '',
  },
  {
    id: 30,
    categoriaEmoji: '🐾',
    categoria: 'Mascota',
    grupoEmoji: '🐶',
    grupo: 'Veterinario',
    subgrupEubgrupo: '',
    tipo: '',
    helperKey: '',
  },
  // Tecnologia
  {
    id: 31,
    categoriaEmoji: '💻',
    categoria: 'Tecnologia',
    grupoEmoji: '📱',
    grupo: 'Telefonia Móvil',
    subgrupEubgrupo: 'Accesorios',
    tipo: '',
    helperKey: '',
  },
  {
    id: 32,
    categoria: 'Tecnologia',
    categoriaEmoji: '💻',
    grupo: 'Telefonia Móvil',
    grupoEmoji: '📱',
    subgrupo: 'Planes',
    subgrupEmoji: '📶',
    tipo: '',
    helperKey: '',
  },
  {
    id: 33,
    categoria: 'Tecnologia',
    categoriaEmoji: '💻',
    grupo: 'Telefonia Móvil',
    grupoEmoji: '📱',
    subgrupo: 'Recargas',
    subgrupEmoji: '🔋',
    tipo: '',
    helperKey: '',
  },
  {
    id: 34,
    categoria: 'Tecnologia',
    categoriaEmoji: '💻',
    grupo: 'Web',
    grupoEmoji: '🌐',
    subgrupo: 'Alojamiento',
    subgrupEmoji: '🖥️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 35,
    categoria: 'Tecnologia',
    categoriaEmoji: '💻',
    grupo: 'Web',
    grupoEmoji: '🌐',
    subgrupo: 'Desarrollo',
    subgrupEmoji: '🛠️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 36,
    categoria: 'Tecnologia',
    categoriaEmoji: '💻',
    grupo: 'Web',
    grupoEmoji: '🌐',
    subgrupo: 'Dominios',
    subgrupEmoji: '🌐',
    tipo: '',
    helperKey: '',
  },
  // Transporte
  {
    id: 37,
    categoria: 'Transporte',
    categoriaEmoji: '🚗',
    grupo: 'Automovil',
    grupoEmoji: '🚗',
    subgrupo: 'Estacionamiento',
    subgrupEmoji: '🅿️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 38,
    categoria: 'Transporte',
    categoriaEmoji: '🚗',
    grupo: 'Automovil',
    grupoEmoji: '🚗',
    subgrupo: 'Gasolina',
    subgrupEmoji: '⛽',
    tipo: '',
    helperKey: '',
  },
  {
    id: 39,
    categoria: 'Transporte',
    categoriaEmoji: '🚗',
    grupo: 'Bicicleta',
    grupoEmoji: '🚲',
    subgrupo: '',
    subgrupEmoji: '🚲',
    tipo: '',
    helperKey: '',
  },
  {
    id: 40,
    categoria: 'Transporte',
    categoriaEmoji: '🚗',
    grupo: 'Taxi',
    grupoEmoji: '🚕',
    subgrupo: '',
    subgrupEmoji: '🚕',
    tipo: '',
    helperKey: '',
  },
  {
    id: 41,
    categoria: 'Transporte',
    categoriaEmoji: '🚗',
    grupo: 'Transporte Público',
    grupoEmoji: '🚌',
    subgrupo: '',
    subgrupEmoji: '🚌',
    tipo: '',
    helperKey: '',
  },
  // Vida y Entretenimiento
  {
    id: 42,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Cuidado Personal',
    grupoEmoji: '💆',
    subgrupo: 'Masajes',
    subgrupEmoji: '💆',
    tipo: '',
    helperKey: '',
  },
  {
    id: 43,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Cuidado Personal',
    grupoEmoji: '💆',
    subgrupo: 'Peluqueria',
    subgrupEmoji: '💇',
    tipo: '',
    helperKey: '',
  },
  {
    id: 44,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Educación y Desarrollo',
    grupoEmoji: '🎓',
    subgrupo: 'Cursos y Clases',
    subgrupEmoji: '🎓',
    tipo: '',
    helperKey: '',
  },
  {
    id: 45,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Educación y Desarrollo',
    grupoEmoji: '🎓',
    subgrupo: 'Libros',
    subgrupEmoji: '📚',
    tipo: '',
    helperKey: '',
  },
  {
    id: 46,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Eventos Fuera de Casa',
    grupoEmoji: '🎭',
    subgrupo: 'Cine',
    subgrupEmoji: '🎬',
    tipo: '',
    helperKey: '',
  },
  {
    id: 47,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Eventos Fuera de Casa',
    grupoEmoji: '🎭',
    subgrupo: 'Conciertos / Festivales',
    subgrupEmoji: '🎤',
    tipo: '',
    helperKey: '',
  },
  {
    id: 48,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Eventos Fuera de Casa',
    grupoEmoji: '🎭',
    subgrupo: 'Eventos Deportivos',
    subgrupEmoji: '🏟️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 49,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Eventos Fuera de Casa',
    grupoEmoji: '🎭',
    subgrupo: 'Teatro',
    subgrupEmoji: '🎭',
    tipo: '',
    helperKey: '',
  },
  {
    id: 50,
    categoriaEmoji: '🎉',
    categoria: 'Vida y Entretenimiento',
    grupoEmoji: '🎉',
    grupo: 'Eventos Sociales',
    subgrupEubgrupo: '',
    tipo: '',
    helperKey: '',
  },
  {
    id: 51,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Fitness',
    grupoEmoji: '🏋️',
    subgrupo: 'Equipo Fitness',
    subgrupEmoji: '🏋️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 52,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Fitness',
    grupoEmoji: '🏋️',
    subgrupo: 'Equipo de Futbol',
    subgrupEmoji: '⚽',
    tipo: '',
    helperKey: '',
  },
  {
    id: 53,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Fitness',
    grupoEmoji: '🏋️',
    subgrupo: 'Gym',
    subgrupEmoji: '🏋️‍♂️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 54,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Fitness',
    grupoEmoji: '🏋️',
    subgrupo: 'Yoga',
    subgrupEmoji: '🧘',
    tipo: '',
    helperKey: '',
  },
  {
    id: 55,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Juegos de Azar | Apuestas',
    grupoEmoji: '🎰',
    subgrupo: '',
    subgrupEmoji: '🎰',
    tipo: '',
    helperKey: '',
  },
  {
    id: 56,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Libros | Audio',
    grupoEmoji: '📖',
    subgrupo: '',
    subgrupEmoji: '📖',
    tipo: '',
    helperKey: '',
  },
  {
    id: 57,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Malos Vicios',
    grupoEmoji: '🚬',
    subgrupo: 'Alcohol',
    subgrupEmoji: '🍺',
    tipo: '',
    helperKey: '',
  },
  {
    id: 58,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Malos Vicios',
    grupoEmoji: '🚬',
    subgrupo: 'Cigarros',
    subgrupEmoji: '🚬',
    tipo: '',
    helperKey: '',
  },
  {
    id: 59,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Malos Vicios',
    grupoEmoji: '🚬',
    subgrupo: 'Drogas',
    subgrupEmoji: '⚠️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 60,
    categoriaEmoji: '🎉',
    categoria: 'Vida y Entretenimiento',
    grupoEmoji: '🎵',
    grupo: 'Pasatiempos',
    subgrupEubgrupo: 'Clases de Baile',
    tipo: '',
    helperKey: '',
  },
  {
    id: 61,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Pasatiempos',
    grupoEmoji: '🎵',
    subgrupo: 'Música',
    subgrupEmoji: '🎵',
    tipo: '',
    helperKey: '',
  },
  {
    id: 62,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Salud',
    grupoEmoji: '🏥',
    subgrupo: 'Consultas Médicas',
    subgrupEmoji: '🏥',
    tipo: '',
    helperKey: '',
  },
  {
    id: 63,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Salud',
    grupoEmoji: '🏥',
    subgrupo: 'Dentista',
    subgrupEmoji: '🦷',
    tipo: '',
    helperKey: '',
  },
  {
    id: 64,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Salud',
    grupoEmoji: '🏥',
    subgrupo: 'Farmacia | Medicinas',
    subgrupEmoji: '💊',
    tipo: '',
    helperKey: '',
  },
  {
    id: 65,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Salud',
    grupoEmoji: '🏥',
    subgrupo: 'Fisioterapia | Acupuntura',
    subgrupEmoji: '👐',
    tipo: '',
    helperKey: '',
  },
  {
    id: 66,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Salud',
    grupoEmoji: '🏥',
    subgrupo: 'Psicologo',
    subgrupEmoji: '🧠',
    tipo: '',
    helperKey: '',
  },
  {
    id: 67,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Streaming',
    grupoEmoji: '🎬',
    subgrupo: 'Amazon Prime',
    subgrupEmoji: '🅰️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 68,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Streaming',
    grupoEmoji: '🎬',
    subgrupo: 'Disney+',
    subgrupEmoji: '🟦',
    tipo: '',
    helperKey: '',
  },
  {
    id: 69,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Streaming',
    grupoEmoji: '🎬',
    subgrupo: 'HBO Max',
    subgrupEmoji: '🎬',
    tipo: '',
    helperKey: '',
  },
  {
    id: 70,
    categoriaEmoji: '🎉',
    categoria: 'Vida y Entretenimiento',
    grupoEmoji: '🎬',
    grupo: 'Streaming',
    subgrupEubgrupo: 'Netflix',
    tipo: '',
    helperKey: '',
  },
  {
    id: 71,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Streaming',
    grupoEmoji: '🎬',
    subgrupo: 'Spotify',
    subgrupEmoji: '🎧',
    tipo: '',
    helperKey: '',
  },
  {
    id: 72,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Viajes',
    grupoEmoji: '✈️',
    subgrupo: 'Actividades',
    subgrupEmoji: '🗺️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 73,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Viajes',
    grupoEmoji: '✈️',
    subgrupo: 'Avión',
    subgrupEmoji: '✈️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 74,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Viajes',
    grupoEmoji: '✈️',
    subgrupo: 'Comida',
    subgrupEmoji: '🍽️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 75,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Viajes',
    grupoEmoji: '✈️',
    subgrupo: 'Hospedaje',
    subgrupEmoji: '🏨',
    tipo: '',
    helperKey: '',
  },
  {
    id: 76,
    categoria: 'Vida y Entretenimiento',
    categoriaEmoji: '🎉',
    grupo: 'Viajes',
    grupoEmoji: '✈️',
    subgrupo: 'Transporte',
    subgrupEmoji: '🚗',
    tipo: '',
    helperKey: '',
  },
  // Vivienda
  {
    id: 77,
    categoria: 'Vivienda',
    categoriaEmoji: '🏠',
    grupo: 'Vivienda',
    grupoEmoji: '🏠',
    subgrupo: 'Internet y Teléfono',
    subgrupEmoji: '📶',
    tipo: '',
    helperKey: '',
  },
  {
    id: 78,
    categoria: 'Vivienda',
    categoriaEmoji: '🏠',
    grupo: 'Vivienda',
    grupoEmoji: '🏠',
    subgrupo: 'Limpieza del Hogar',
    subgrupEmoji: '🧹',
    tipo: '',
    helperKey: '',
  },
  {
    id: 79,
    categoria: 'Vivienda',
    categoriaEmoji: '🏠',
    grupo: 'Vivienda',
    grupoEmoji: '🏠',
    subgrupo: 'Mantenimiento Copilco',
    subgrupEmoji: '🛠️',
    tipo: '',
    helperKey: '',
  },
  {
    id: 80,
    categoria: 'Vivienda',
    categoriaEmoji: '🏠',
    grupo: 'Vivienda',
    grupoEmoji: '🏠',
    subgrupo: 'Reparaciones',
    subgrupEmoji: '🔨',
    tipo: '',
    helperKey: '',
  },
  {
    id: 81,
    categoriaEmoji: '🏠',
    categoria: 'Vivienda',
    grupoEmoji: '🏠',
    grupo: 'Vivienda',
    subgrupEubgrupo: 'Servicios - Agua',
    tipo: '',
    helperKey: '',
  },
  {
    id: 82,
    categoria: 'Vivienda',
    categoriaEmoji: '🏠',
    grupo: 'Vivienda',
    grupoEmoji: '🏠',
    subgrupo: 'Servicios - Gas',
    subgrupEmoji: '🔥',
    tipo: '',
    helperKey: '',
  },
  {
    id: 83,
    categoria: 'Vivienda',
    categoriaEmoji: '🏠',
    grupo: 'Vivienda',
    grupoEmoji: '🏠',
    subgrupo: 'Servicios - Luz',
    subgrupEmoji: '💡',
    tipo: '',
    helperKey: '',
  },
];

export const dataCategoriasGastos = rawDataCategoriasGastos;
