export const CategoriasGastos = [
  {
    Alimentos: {
      Comercios: ['Bar', 'Café', 'Restaurante'],
      Comida: ['A Domicilio', 'Callejera', 'Comida Rápida', 'Tianguis', 'Tiendita'],
      Despensa: ['Mercado', 'Supermercado'],
    },
  },
  {
    Compras: {
      Accesorios: [],
      'Artículos para el Hogar': [],
      Electrónica: [],
      Herramientas: [],
      'Higiene Personal': [],
      Muebles: [],
      Oficina: [],
      'Productos de Limpieza para el Hogar': [],
      Regalos: [],
      'Ropa y Calzado': [],
      'Tiempo libre': [],
    },
  },
  {
    'Gastos Financieros': {
      Comisiones: [],
      Impuestos: [],
      Intereses: [],
    },
  },
  {
    Mascota: {
      Baño: [],
      Croquetas: [],
      'Juguetes y Accesorios': [],
      'Medicinas y Suplementos': [],
      Otros: [],
      Veterinario: [],
    },
  },
  {
    Tecnologia: {
      'Telefonia Móvil': ['Accesorios', 'Planes', 'Recargas'],
      Web: ['Alojamiento', 'Desarrollo', 'Dominios'],
    },
  },
  {
    Transporte: {
      Automovil: ['Estacionamiento', 'Gasolina'],
      Bicicleta: [],
      Taxi: [],
      'Transporte Público': [],
    },
  },
  {
    'Vida y Entretenimiento': {
      'Cuidado Personal': ['Masajes', 'Peluqueria'],
      'Educación y Desarrollo': ['Cursos y Clases', 'Libros'],
      'Eventos Fuera de Casa': ['Cine', 'Conciertos / Festivales', 'Eventos Deportivos', 'Teatro'],
      'Eventos Sociales': [],
      Fitness: ['Equipo Fitness', 'Equipo de Futbol', 'Gym', 'Yoga'],
      'Juegos de Azar | Apuestas': [],
      'Libros | Audio': [],
      'Malos Vicios': ['Alcohol', 'Cigarros', 'Drogas'],
      Pasatiempos: ['Clases de Baile', 'Música'],
      Salud: [
        'Consultas Médicas',
        'Dentista',
        'Farmacia | Medicinas',
        'Fisioterapia | Acupuntura',
        'Psicologo',
      ],
      Streaming: ['Amazon Prime', 'Disney+', 'HBO Max', 'Netflix', 'Spotify'],
      Viajes: ['Actividades', 'Avión', 'Comida', 'Hospedaje', 'Transporte'],
    },
  },
  {
    Vivienda: {
      'Internet y Teléfono': [],
      'Limpieza del Hogar': [],
      'Mantenimiento Copilco': [],
      Reparaciones: [],
      Servicios: ['Agua', 'Gas', 'Luz'],
    },
  },
];

export const dataCategoriasGastos = [
  // Alimentos
  {
    categoria: 'Alimentos',
    grupo: 'Comercios',
    subgrupo: 'Bar',
    emoji: '🍺',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Alimentos',
    grupo: 'Comercios',
    subgrupo: 'Café',
    emoji: '☕',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Alimentos',
    grupo: 'Comercios',
    subgrupo: 'Restaurante',
    emoji: '🍽️',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Alimentos',
    grupo: 'Comida',
    subgrupo: 'A Domicilio',
    emoji: '🏠',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Alimentos',
    grupo: 'Comida',
    subgrupo: 'Callejera',
    emoji: '🌮',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Alimentos',
    grupo: 'Comida',
    subgrupo: 'Comida Rápida',
    emoji: '🍔',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Alimentos',
    grupo: 'Comida',
    subgrupo: 'Tianguis',
    emoji: '🛒',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Alimentos',
    grupo: 'Comida',
    subgrupo: 'Tiendita',
    emoji: '🏪',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Alimentos',
    grupo: 'Despensa',
    subgrupo: 'Mercado',
    emoji: '🥬',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Alimentos',
    grupo: 'Despensa',
    subgrupo: 'Supermercado',
    emoji: '🛍️',
    tipo: '',
    helperKey: '',
  },

  // Compras
  { categoria: 'Compras', grupo: 'Accesorios', subgrupo: '', emoji: '👜', tipo: '', helperKey: '' },
  {
    categoria: 'Compras',
    grupo: 'Artículos para el Hogar',
    subgrupo: '',
    emoji: '🏠',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Compras',
    grupo: 'Electrónica',
    subgrupo: '',
    emoji: '💻',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Compras',
    grupo: 'Herramientas',
    subgrupo: '',
    emoji: '🔧',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Compras',
    grupo: 'Higiene Personal',
    subgrupo: '',
    emoji: '🧴',
    tipo: '',
    helperKey: '',
  },
  { categoria: 'Compras', grupo: 'Muebles', subgrupo: '', emoji: '🛋️', tipo: '', helperKey: '' },
  { categoria: 'Compras', grupo: 'Oficina', subgrupo: '', emoji: '📎', tipo: '', helperKey: '' },
  {
    categoria: 'Compras',
    grupo: 'Productos de Limpieza para el Hogar',
    subgrupo: '',
    emoji: '🧽',
    tipo: '',
    helperKey: '',
  },
  { categoria: 'Compras', grupo: 'Regalos', subgrupo: '', emoji: '🎁', tipo: '', helperKey: '' },
  {
    categoria: 'Compras',
    grupo: 'Ropa y Calzado',
    subgrupo: '',
    emoji: '👗',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Compras',
    grupo: 'Tiempo libre',
    subgrupo: '',
    emoji: '🎲',
    tipo: '',
    helperKey: '',
  },

  // Gastos Financieros
  {
    categoria: 'Gastos Financieros',
    grupo: 'Gastos Financieros',
    subgrupo: 'Comisiones',
    emoji: '💳',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Gastos Financieros',
    grupo: 'Gastos Financieros',
    subgrupo: 'Impuestos',
    emoji: '🧾',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Gastos Financieros',
    grupo: 'Gastos Financieros',
    subgrupo: 'Intereses',
    emoji: '📈',
    tipo: '',
    helperKey: '',
  },

  // Mascota
  {
    categoria: 'Mascota',
    grupo: 'Mascota',
    subgrupo: 'Baño',
    emoji: '🛁',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Mascota',
    grupo: 'Mascota',
    subgrupo: 'Croquetas',
    emoji: '🍖',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Mascota',
    grupo: 'Mascota',
    subgrupo: 'Juguetes y Accesorios',
    emoji: '🧸',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Mascota',
    grupo: 'Mascota',
    subgrupo: 'Medicinas y Suplementos',
    emoji: '💊',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Mascota',
    grupo: 'Mascota',
    subgrupo: 'Otros',
    emoji: '🔎',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Mascota',
    grupo: 'Mascota',
    subgrupo: 'Veterinario',
    emoji: '🩺',
    tipo: '',
    helperKey: '',
  },

  // Tecnologia
  {
    categoria: 'Tecnologia',
    grupo: 'Telefonia Móvil',
    subgrupo: 'Accesorios',
    emoji: '📱',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Tecnologia',
    grupo: 'Telefonia Móvil',
    subgrupo: 'Planes',
    emoji: '📶',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Tecnologia',
    grupo: 'Telefonia Móvil',
    subgrupo: 'Recargas',
    emoji: '🔋',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Tecnologia',
    grupo: 'Web',
    subgrupo: 'Alojamiento',
    emoji: '🖥️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Tecnologia',
    grupo: 'Web',
    subgrupo: 'Desarrollo',
    emoji: '🛠️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Tecnologia',
    grupo: 'Web',
    subgrupo: 'Dominios',
    emoji: '🌐',
    tipo: '',
    helperKey: '',
  },

  // Transporte
  {
    categoria: 'Transporte',
    grupo: 'Automovil',
    subgrupo: 'Estacionamiento',
    emoji: '🅿️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Transporte',
    grupo: 'Automovil',
    subgrupo: 'Gasolina',
    emoji: '⛽',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Transporte',
    grupo: 'Bicicleta',
    subgrupo: '',
    emoji: '🚲',
    tipo: '',
    helperKey: '',
  },
  { categoria: 'Transporte', grupo: 'Taxi', subgrupo: '', emoji: '🚕', tipo: '', helperKey: '' },
  {
    categoria: 'Transporte',
    grupo: 'Transporte Público',
    subgrupo: '',
    emoji: '🚌',
    tipo: '',
    helperKey: '',
  },

  // Vida y Entretenimiento
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Cuidado Personal',
    subgrupo: 'Masajes',
    emoji: '💆',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Cuidado Personal',
    subgrupo: 'Peluqueria',
    emoji: '💇',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Educación y Desarrollo',
    subgrupo: 'Cursos y Clases',
    emoji: '🎓',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Educación y Desarrollo',
    subgrupo: 'Libros',
    emoji: '📚',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Eventos Fuera de Casa',
    subgrupo: 'Cine',
    emoji: '🎬',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Eventos Fuera de Casa',
    subgrupo: 'Conciertos / Festivales',
    emoji: '🎤',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Eventos Fuera de Casa',
    subgrupo: 'Eventos Deportivos',
    emoji: '🏟️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Eventos Fuera de Casa',
    subgrupo: 'Teatro',
    emoji: '🎭',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Eventos Sociales',
    subgrupo: '',
    emoji: '🥳',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Fitness',
    subgrupo: 'Equipo Fitness',
    emoji: '🏋️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Fitness',
    subgrupo: 'Equipo de Futbol',
    emoji: '⚽',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Fitness',
    subgrupo: 'Gym',
    emoji: '🏋️‍♂️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Fitness',
    subgrupo: 'Yoga',
    emoji: '🧘',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Juegos de Azar | Apuestas',
    subgrupo: '',
    emoji: '🎰',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Libros | Audio',
    subgrupo: '',
    emoji: '📖',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Malos Vicios',
    subgrupo: 'Alcohol',
    emoji: '🍺',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Malos Vicios',
    subgrupo: 'Cigarros',
    emoji: '🚬',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Malos Vicios',
    subgrupo: 'Drogas',
    emoji: '⚠️',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Pasatiempos',
    subgrupo: 'Clases de Baile',
    emoji: '💃',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Pasatiempos',
    subgrupo: 'Música',
    emoji: '🎵',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Salud',
    subgrupo: 'Consultas Médicas',
    emoji: '🏥',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Salud',
    subgrupo: 'Dentista',
    emoji: '🦷',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Salud',
    subgrupo: 'Farmacia | Medicinas',
    emoji: '💊',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Salud',
    subgrupo: 'Fisioterapia | Acupuntura',
    emoji: '👐',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Salud',
    subgrupo: 'Psicologo',
    emoji: '🧠',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Streaming',
    subgrupo: 'Amazon Prime',
    emoji: '🅰️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Streaming',
    subgrupo: 'Disney+',
    emoji: '🟦',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Streaming',
    subgrupo: 'HBO Max',
    emoji: '🎬',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Streaming',
    subgrupo: 'Netflix',
    emoji: '📺',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Streaming',
    subgrupo: 'Spotify',
    emoji: '🎧',
    tipo: '',
    helperKey: '',
  },

  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Viajes',
    subgrupo: 'Actividades',
    emoji: '🗺️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Viajes',
    subgrupo: 'Avión',
    emoji: '✈️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Viajes',
    subgrupo: 'Comida',
    emoji: '🍽️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Viajes',
    subgrupo: 'Hospedaje',
    emoji: '🏨',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vida y Entretenimiento',
    grupo: 'Viajes',
    subgrupo: 'Transporte',
    emoji: '🚗',
    tipo: '',
    helperKey: '',
  },

  // Vivienda
  {
    categoria: 'Vivienda',
    grupo: 'Vivienda',
    subgrupo: 'Internet y Teléfono',
    emoji: '📶',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vivienda',
    grupo: 'Vivienda',
    subgrupo: 'Limpieza del Hogar',
    emoji: '🧹',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vivienda',
    grupo: 'Vivienda',
    subgrupo: 'Mantenimiento Copilco',
    emoji: '🛠️',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vivienda',
    grupo: 'Vivienda',
    subgrupo: 'Reparaciones',
    emoji: '🔨',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vivienda',
    grupo: 'Vivienda',
    subgrupo: 'Servicios - Agua',
    emoji: '🚰',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vivienda',
    grupo: 'Vivienda',
    subgrupo: 'Servicios - Gas',
    emoji: '🔥',
    tipo: '',
    helperKey: '',
  },
  {
    categoria: 'Vivienda',
    grupo: 'Vivienda',
    subgrupo: 'Servicios - Luz',
    emoji: '💡',
    tipo: '',
    helperKey: '',
  },
];

export const data = [
  {
    emoji: '🍎',
    value: 'Apples',
    description:
      'Crisp and refreshing fruit. Apples are known for their versatility and nutritional benefits. They come in a variety of flavors and are great for snacking, baking, or adding to salads.',
  },
  {
    emoji: '🍌',
    value: 'Bananas',
    description:
      'Naturally sweet and potassium-rich fruit. Bananas are a popular choice for their energy-boosting properties and can be enjoyed as a quick snack, added to smoothies, or used in baking.',
  },
  {
    emoji: '🥦',
    value: 'Broccoli',
    description:
      'Nutrient-packed green vegetable. Broccoli is packed with vitamins, minerals, and fiber. It has a distinct flavor and can be enjoyed steamed, roasted, or added to stir-fries.',
  },
];
